name: Dev - Build, Test & Pack

on:
  push:
    branches:
    - dev
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Pull & update submodule recursively
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote
    - name: Restore submodule dependencies
      run: dotnet restore Radarr/src/Radarr.sln
    - name: Restore dependencies
      run: dotnet restore
    - name: Update integration tests appsettings.json
      uses: microsoft/variable-substitution@v1 
      with:
          files: 'RadarrApiWrapper.IntegrationTests/appsettings.json'
      env:
          ApiBaseUrl: ${{ secrets.APIBASEURL }}
          ApiKey: ${{ secrets.APIKEY }}
    - name: Build submodule
      run: dotnet build Radarr/src/Radarr.sln --no-restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
